name: Erik Weisenburger
favicon: null
layout_spectrum: 0
typography_spectrum: 0.75594
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8b9a9d'
    - '#24252a'
    - '#557174'
    - '#415e62'
    - '#28454d'
  brandStrength: 0.9375
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0
purpose: []
